# Generated by Django 5.1.5 on 2025-02-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shifts',
            old_name='shifts',
            new_name='doctor',
        ),
    ]
